# Generated by Django 5.1.4 on 2025-03-06 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='Название')),
                ('edu_form', models.CharField(max_length=15, verbose_name='Форма обучения')),
                ('slug', models.SlugField(blank=True, max_length=256, null=True, unique=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, default='Описание программы еще не добавлено', null=True, verbose_name='Описание')),
                ('sertificate', models.URLField(blank=True, max_length=256, null=True, verbose_name='Сертификат об окончании (URL)')),
                ('structure', models.TextField(blank=True, default='Структура программы еще не добавлена', max_length=256, null=True, verbose_name='Структура программы')),
                ('hours', models.IntegerField(blank=True, null=True, verbose_name='Количество часов')),
                ('image', models.ImageField(blank=True, null=True, upload_to='curse_image', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Направление',
                'verbose_name_plural': 'Направления',
                'db_table': 'curse',
            },
        ),
        migrations.CreateModel(
            name='Disciplines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Название')),
                ('curse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.curses', verbose_name='Направление')),
            ],
            options={
                'verbose_name': 'Дисциплина',
                'verbose_name_plural': 'Дисциплины',
                'db_table': 'discipline',
            },
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Название')),
                ('url', models.URLField(max_length=150, unique=True, verbose_name='Ссылка на документ')),
                ('curse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.curses', verbose_name='Направление')),
            ],
            options={
                'verbose_name': 'Документ',
                'verbose_name_plural': 'Добавить документы',
                'db_table': 'document',
            },
        ),
        migrations.CreateModel(
            name='Lecturers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, unique=True, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=150, unique=True, verbose_name='Фамилия')),
                ('surname', models.CharField(max_length=150, unique=True, verbose_name='Отчество')),
                ('education', models.CharField(blank=True, max_length=150, null=True, unique=True, verbose_name='Образование')),
                ('description', models.CharField(blank=True, max_length=256, null=True, unique=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='lecturer_image', verbose_name='Изображение')),
                ('curse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.curses', verbose_name='Направление')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.disciplines', verbose_name='Дисциплина')),
            ],
            options={
                'verbose_name': 'Преподаватель',
                'verbose_name_plural': 'Преподаватели',
                'db_table': 'lecturer',
            },
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=150, verbose_name='Фамилия')),
                ('surname', models.CharField(blank=True, max_length=150, null=True, verbose_name='Отчество')),
                ('birth_date', models.DateField(blank=True, max_length=10, null=True, verbose_name='Дата рождения')),
                ('curse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.curses', verbose_name='Направление')),
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Студенты',
                'db_table': 'student',
            },
        ),
    ]
