# Generated by Django 5.1.4 on 2025-03-01 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Название')),
                ('edu_form', models.CharField(max_length=15, verbose_name='Форма обучения')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('documents', models.CharField(max_length=150, unique=True, verbose_name='Документы')),
                ('sertificate', models.CharField(max_length=150, unique=True, verbose_name='Сертификат об окончании')),
                ('structure', models.CharField(max_length=150, unique=True, verbose_name='Структура программы')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Направление',
                'verbose_name_plural': 'Направления',
                'db_table': 'curse',
            },
        ),
        migrations.CreateModel(
            name='Disciplines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Название')),
                ('curse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.curses', verbose_name='Направление')),
            ],
            options={
                'verbose_name': 'Дисциплина',
                'verbose_name_plural': 'Дисциплины',
                'db_table': 'discipline',
            },
        ),
        migrations.CreateModel(
            name='Lecturers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, unique=True, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=150, unique=True, verbose_name='Фамилия')),
                ('surname', models.CharField(max_length=150, unique=True, verbose_name='Отчество')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.disciplines', verbose_name='Дисциплина')),
            ],
            options={
                'verbose_name': 'Преподаватель',
                'verbose_name_plural': 'Преподаватели',
                'db_table': 'lecturer',
            },
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=150, verbose_name='Фамилия')),
                ('surname', models.CharField(blank=True, max_length=150, null=True, verbose_name='Отчество')),
                ('curse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.curses', verbose_name='Направление')),
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Студенты',
                'db_table': 'student',
            },
        ),
    ]
