# Generated by Django 5.1.4 on 2025-03-01 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curses',
            name='documents',
            field=models.CharField(max_length=150, unique=True, verbose_name='Документ (URL)'),
        ),
        migrations.AlterField(
            model_name='curses',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='curse_images', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='curses',
            name='sertificate',
            field=models.CharField(max_length=150, unique=True, verbose_name='Сертификат об окончании (URL)'),
        ),
    ]
