# Generated by Django 5.1.4 on 2025-03-02 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_curses_documents_alter_curses_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curses',
            name='documents',
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Название')),
                ('url', models.URLField(max_length=150, unique=True, verbose_name='Ссылка на документ')),
                ('curse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.curses', verbose_name='Направление')),
            ],
        ),
    ]
