# Generated by Django 5.1.4 on 2025-03-07 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_students_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='curse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.curses', verbose_name='Направление'),
        ),
    ]
