# Generated by Django 5.1.4 on 2025-03-02 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_curses_documents_documents'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Documents',
            new_name='Document',
        ),
        migrations.AlterModelTable(
            name='document',
            table='document',
        ),
    ]
