# Generated by Django 5.1.4 on 2025-03-02 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_documents_document_alter_document_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curses',
            name='structure',
            field=models.TextField(max_length=150, unique=True, verbose_name='Структура программы'),
        ),
    ]
