# Generated by Django 5.1.4 on 2025-03-07 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_students_curse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='phone',
            field=models.CharField(blank=True, null=True, verbose_name='Номер телефона'),
        ),
    ]
