# Generated by Django 5.1.4 on 2025-03-02 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_curses_structure'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'verbose_name': 'Документ', 'verbose_name_plural': 'Документы'},
        ),
        migrations.AlterField(
            model_name='curses',
            name='sertificate',
            field=models.URLField(max_length=150, unique=True, verbose_name='Сертификат об окончании (URL)'),
        ),
    ]
