# Generated by Django 5.1.4 on 2025-03-07 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_students_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='slug',
        ),
        migrations.AddField(
            model_name='students',
            name='description',
            field=models.CharField(blank=True, max_length=256, null=True, unique=True, verbose_name='Примечания'),
        ),
    ]
