# Generated by Django 5.1.4 on 2025-03-07 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_students_slug_students_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='curse_is_paid',
            field=models.BooleanField(default=False, verbose_name='Оплачено?'),
        ),
    ]
