# Generated by Django 5.1.4 on 2025-03-07 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_students_curse_is_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Примечания'),
        ),
    ]
