# Generated by Django 5.1.4 on 2025-03-07 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_students_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curses',
            name='sertificate',
            field=models.URLField(blank=True, null=True, verbose_name='Сертификат об окончании (URL)'),
        ),
        migrations.AlterField(
            model_name='curses',
            name='structure',
            field=models.TextField(blank=True, default='Структура программы еще не добавлена', null=True, verbose_name='Структура программы'),
        ),
        migrations.AlterField(
            model_name='lecturers',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
