# Generated by Django 5.1.4 on 2025-03-11 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_curses_sertificate_alter_curses_structure_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Why Lead Generation is Key for Business Growth', max_length=150, verbose_name='Заголовок')),
                ('subtitle', models.TextField(default='A small river named Duden flows by their place and supplies it with the necessary regelialia.', verbose_name='Подзаголовок')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата публикации')),
                ('image', models.ImageField(blank=True, default='static/images/person-default.png', null=True, upload_to='news_image', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'db_table': 'news',
            },
        ),
    ]
