# Generated by Django 5.1.4 on 2025-03-11 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст новости'),
        ),
    ]
