# Generated by Django 5.1.4 on 2025-03-13 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_newstag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='news_image', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='newstag',
            name='new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.news', verbose_name='Новость'),
        ),
    ]
