# Generated by Django 5.1.4 on 2025-03-13 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_news_image_alter_newstag_new'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curses',
            name='hours',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Количество часов'),
        ),
        migrations.AlterField(
            model_name='news',
            name='subtitle',
            field=models.TextField(default='Подзаголовок интересной новости', verbose_name='Подзаголовок'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(default='Заголовок интересной новости', max_length=150, verbose_name='Заголовок'),
        ),
    ]
