# Generated by Django 5.1.4 on 2025-03-13 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_curses_hours_alter_news_subtitle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='paid_or_free',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
