# Generated by Django 5.1.4 on 2025-03-13 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_students_paid_or_free'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='paid_or_free',
            field=models.CharField(blank=True, default='б', max_length=15, null=True),
        ),
    ]
