# Generated by Django 5.1.4 on 2025-03-13 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_students_paid_or_free'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='students',
            name='paid_or_free',
        ),
        migrations.AddField(
            model_name='curses',
            name='paid_or_free',
            field=models.CharField(blank=True, default='б', max_length=2, null=True),
        ),
    ]
