# Generated by Django 5.1.4 on 2025-03-19 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_curses_paid_or_free'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(default='light', max_length=5)),
            ],
        ),
        migrations.AlterField(
            model_name='curses',
            name='paid_or_free',
            field=models.CharField(blank=True, default='б', max_length=2, null=True, verbose_name='Бюджет/Внебюджет (б/вб)'),
        ),
    ]
