# Generated by Django 5.1.4 on 2025-03-20 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_settings_alter_curses_paid_or_free'),
    ]

    operations = [
        migrations.AddField(
            model_name='curses',
            name='price',
            field=models.IntegerField(blank=True, default=106297, null=True, verbose_name='Цена, в руб.'),
        ),
    ]
