# Generated by Django 5.1.4 on 2025-03-20 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_alter_curses_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='curses',
            name='hours',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество часов'),
        ),
        migrations.AlterField(
            model_name='curses',
            name='price',
            field=models.IntegerField(blank=True, default=137299, null=True, verbose_name='Цена, в руб.'),
        ),
    ]
