# Generated by Django 5.1.4 on 2025-04-01 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_curses_hours_alter_curses_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curses',
            name='price',
            field=models.IntegerField(blank=True, default=117313, null=True, verbose_name='Цена, в руб.'),
        ),
        migrations.AlterField(
            model_name='lecturers',
            name='first_name',
            field=models.CharField(max_length=150, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='lecturers',
            name='last_name',
            field=models.CharField(max_length=150, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='lecturers',
            name='surname',
            field=models.CharField(max_length=150, verbose_name='Отчество'),
        ),
    ]
